**K-Nearest Neighbour Classifier on the IRIS Dataset**

Here I have imported some libraries:

In [1]:
import pandas as pd
import numpy as np

Here I have imported the dataset i am using for this project

In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

Here i am seeing the data inside the dataset 'keys'

In [3]:
print("Keys of the iris_dataset :\n{}".format(iris_dataset.keys()))

Keys of the iris_dataset :
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


Here i am seeing the first 200 characters of the DESCR

In [4]:
print(iris_dataset['DESCR'][:200]+"\n......")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
......


Here i am seeing the value of the target_names 

In [5]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


Here i am seeing the values of the features_names

In [6]:
print("Features Names: {}".format(iris_dataset['feature_names']))

Features Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Here i am seeing the type of the data

In [7]:
print("Type of Data:{}".format(type(iris_dataset['data'])))

Type of Data:<class 'numpy.ndarray'>


Here i am seeing the Shape of the data

In [8]:
print("Shape of Data: {}".format(iris_dataset['data'].shape))

Shape of Data: (150, 4)


Here i am seeing the first 5 rows of the data

In [9]:
#Individual rows can be called as samples/instances/datapoints
#And each of the row can be called as attributes/features 
print("First 5 rows of the data : \n{}".format(iris_dataset['data'][:5]))

First 5 rows of the data : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Here i am seeing the type of the target

In [10]:
print("Type of Target: {}".format(type(iris_dataset['target'])))

Type of Target: <class 'numpy.ndarray'>


Here i am seeing the shape of the target

In [11]:
print("Shape of Target: {}".format(iris_dataset['target'].shape))

Shape of Target: (150,)


Here i am seeing the value of the target

In [12]:
print("Target:{} ".format(iris_dataset['target']))

Target:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 


Here I'm spillting the data into 75 and 25 percentages for training and testing purposes respectively

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
                   iris_dataset['data'], iris_dataset['target'], random_state=0)

Checking the shape of the X_train,y_train,X_test,y_test

In [14]:
print("X_train_shape: {}".format(X_train.shape))
print("y_train_shape: {}".format(y_train.shape))
print("X_test_shape: {}".format(X_test.shape))
print("y_test_shape: {}".format(y_test.shape))

X_train_shape: (112, 4)
y_train_shape: (112,)
X_test_shape: (38, 4)
y_test_shape: (38,)


Here I'm making a model i.e. making a bot

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Here I'm training the model by the training data

In [16]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

Predicting for a new data

In [17]:
X_new = np.array([[5,2.9,1,0.2]])

print("X_new shape: {}".format(X_new.shape))

X_new shape: (1, 4)


In [18]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Prediction target names: {}".format(
      iris_dataset['target_names'][prediction]))

Prediction: [0]
Prediction target names: ['setosa']


Evaluating the model

In [19]:
y_pred = knn.predict(X_test)
print("Test set predictions: \n {}".format(y_pred))

Test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Checking out the accuracy of our model

In [20]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
